### ISSUE TITLE
Install lua deps on openWrt 18.06

### ISSUE THREAD

**Issue by etravassos** [CIRALabs/securehomegateway-mud#1]
Luarocks fails when trying to install anything. gcc doesnt seem to be properly linked to lua.

```bash
luarocks install lua-resty-dns-client
...
gcc -O2 -fPIC -I/build/openwrt-18.06/slaves/phase2/x86_64/build/sdk/staging_dir/hostpkg/include -c src/lfs.c -o src/lfs.o
src/lfs.c:66:17: fatal error: lua.h: No such file or directory
compilation terminated.
```
 - Apparently 'liblua5.1-0-dev' is needed but it's not available through opkg. So im not sure how to link gcc to the lua files.

**Comment by etravassos** [comment]
Fixed by manually copying content of liblua dev pack into the system.

```bash
/usr/include/lauxlib.h
/usr/include/lua.h
/usr/include/lua.hpp
/usr/include/luaconf.h
/usr/include/lualib.h
/usr/lib64/liblua.so
/usr/lib64/pkgconfig/lua.pc

```
https://centos.pkgs.org/7/centos-x86_64/lua-devel-5.1.4-15.el7.x86_64.rpm.html

**Comment by mcr** [comment]
Elson Oliveira <notifications@github.com> wrote:
    > Fixed by manually copying content of liblua dev pack into the system.

Does this mean that you are using a compiler to compile the associated
things?

**Comment by etravassos** [comment]
I ended up using a lib written in pure Lua to resolve the urls, so no compiling was actually needed. However luarocks does use gcc when it needs to compile deps.
